package miniprojet;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Grave
 */
public class Mastermind extends javax.swing.JFrame {

    /**
     * Creates new form Mastermind
     */
    public Mastermind() {
        initComponents();
        int nbLignes = 10;
        int nbColonnes = 4;
        PanneauCombinaison.setLayout(new GridLayout(nbLignes, nbColonnes));
        for (int i=0; i < nbLignes; i++) {
            for (int j=0; j < nbColonnes; j++ ) {
                JButton bouton_tentatives = new JButton(); // création d'un bouton
                PanneauCombinaison.add(bouton_tentatives); // ajout au Jpanel PanneauGrille  
  }
}       
        int nbcolonnes = 8;   
        int nbligne = 1;
        BoutonsChoix.setLayout(new GridLayout(nbligne, nbcolonnes));
        for (int k=0; k < nbcolonnes; k++ ){
            
            JButton bouton_choix = new JButton(); // création d'un bouton
            BoutonsChoix.add(bouton_choix); // ajout au Jpanel PanneauGrille
        }
        Indices.setLayout(new GridLayout(nbLignes, 1));
         for (int i=0; i < nbLignes; i++) {

                JLabel bouton_indices = new JLabel(); // création d'un bouton
                Indices.add(bouton_indices); // ajout au Jpanel PanneauGrille  
        
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonsChoix = new javax.swing.JPanel();
        Boutons_valider_quitter = new javax.swing.JPanel();
        Bouton_valider = new javax.swing.JButton();
        Bouton_quitter = new javax.swing.JButton();
        Bouton_regle = new javax.swing.JButton();
        Indices = new javax.swing.JPanel();
        PanneauCombinaison = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 700));
        setSize(new java.awt.Dimension(640, 700));

        BoutonsChoix.setBackground(new java.awt.Color(204, 0, 204));
        BoutonsChoix.setMinimumSize(new java.awt.Dimension(100, 100));
        BoutonsChoix.setPreferredSize(new java.awt.Dimension(640, 76));

        javax.swing.GroupLayout BoutonsChoixLayout = new javax.swing.GroupLayout(BoutonsChoix);
        BoutonsChoix.setLayout(BoutonsChoixLayout);
        BoutonsChoixLayout.setHorizontalGroup(
            BoutonsChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        BoutonsChoixLayout.setVerticalGroup(
            BoutonsChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(BoutonsChoix, java.awt.BorderLayout.PAGE_END);

        Boutons_valider_quitter.setBackground(new java.awt.Color(0, 255, 204));
        Boutons_valider_quitter.setPreferredSize(new java.awt.Dimension(100, 300));

        Bouton_valider.setText("Bouton_valider");
        Bouton_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_validerActionPerformed(evt);
            }
        });

        Bouton_quitter.setText("Bouton_quitter");

        Bouton_regle.setText("Règle");
        Bouton_regle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_regleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Boutons_valider_quitterLayout = new javax.swing.GroupLayout(Boutons_valider_quitter);
        Boutons_valider_quitter.setLayout(Boutons_valider_quitterLayout);
        Boutons_valider_quitterLayout.setHorizontalGroup(
            Boutons_valider_quitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Boutons_valider_quitterLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(Boutons_valider_quitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bouton_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bouton_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bouton_regle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        Boutons_valider_quitterLayout.setVerticalGroup(
            Boutons_valider_quitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boutons_valider_quitterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bouton_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Bouton_regle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(Bouton_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(Boutons_valider_quitter, java.awt.BorderLayout.LINE_END);

        Indices.setBackground(new java.awt.Color(0, 102, 255));
        Indices.setPreferredSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout IndicesLayout = new javax.swing.GroupLayout(Indices);
        Indices.setLayout(IndicesLayout);
        IndicesLayout.setHorizontalGroup(
            IndicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        IndicesLayout.setVerticalGroup(
            IndicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        getContentPane().add(Indices, java.awt.BorderLayout.LINE_START);

        PanneauCombinaison.setBackground(new java.awt.Color(255, 153, 0));
        PanneauCombinaison.setMaximumSize(new java.awt.Dimension(32767, 3000));
        PanneauCombinaison.setPreferredSize(new java.awt.Dimension(412, 300));

        javax.swing.GroupLayout PanneauCombinaisonLayout = new javax.swing.GroupLayout(PanneauCombinaison);
        PanneauCombinaison.setLayout(PanneauCombinaisonLayout);
        PanneauCombinaisonLayout.setHorizontalGroup(
            PanneauCombinaisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        PanneauCombinaisonLayout.setVerticalGroup(
            PanneauCombinaisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauCombinaison, java.awt.BorderLayout.CENTER);
        PanneauCombinaison.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_regleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_regleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bouton_regleActionPerformed

    private void Bouton_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bouton_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mastermind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_quitter;
    private javax.swing.JButton Bouton_regle;
    private javax.swing.JButton Bouton_valider;
    private javax.swing.JPanel BoutonsChoix;
    private javax.swing.JPanel Boutons_valider_quitter;
    private javax.swing.JPanel Indices;
    private javax.swing.JPanel PanneauCombinaison;
    // End of variables declaration//GEN-END:variables
}
